FROM python:3.13-slim

WORKDIR /app

COPY python-api/requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

COPY python-api /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
